<?php

namespace App\Console\Commands;

use App\Models\AbsenceExcuse;
use App\Models\AbsenceExcuseMakeup;
use App\Models\Student;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class SeedExcelAbsenceData extends Command
{
    protected $signature = 'absence:seed-excel';
    protected $description = 'Seed absence excuses from Excel data with makeups, documents and certificates';

    public function handle()
    {
        $records = $this->getData();

        $imported = 0;
        $makeupsCreated = 0;
        $updated = 0;
        $skipped = 0;
        $errors = [];

        foreach ($records as $i => $record) {
            $studentIdNumber = $record['student_id_number'];
            $subjects = json_decode($record['subjects'], true);
            $docLink = $record['doc_link'];
            $certData = json_decode($record['certificate'], true);
            $certPdf = $certData['url_pdf'] ?? null;
            $reviewedByData = json_decode($record['reviewed_by'], true);
            $reviewedByName = $reviewedByData['custom_full_name'] ?? 'Talabnoma tizimi';
            $reviewedById = $reviewedByData['custom_user_id'] ?? null;

            // Find student
            $student = Student::where('student_id_number', $studentIdNumber)->first();
            if (!$student) {
                $student = Student::where('hemis_id', $studentIdNumber)->first();
            }
            if (!$student) {
                $errors[] = "Row " . ($i + 1) . ": Student not found: {$studentIdNumber}";
                continue;
            }

            // Calculate date range from subjects
            $allDates = [];
            foreach ($subjects as $subj) {
                $dates = $subj['dates'];
                if (!empty($dates['jn']['start'])) $allDates[] = Carbon::createFromFormat('d.m.Y', $dates['jn']['start']);
                if (!empty($dates['jn']['end'])) $allDates[] = Carbon::createFromFormat('d.m.Y', $dates['jn']['end']);
                if (!empty($dates['on'])) $allDates[] = Carbon::createFromFormat('d.m.Y', $dates['on']);
                if (!empty($dates['yn'])) $allDates[] = Carbon::createFromFormat('d.m.Y', $dates['yn']);
                if (!empty($dates['yn_test'])) $allDates[] = Carbon::createFromFormat('d.m.Y', $dates['yn_test']);
            }

            if (empty($allDates)) {
                $errors[] = "Row " . ($i + 1) . ": No dates found for {$studentIdNumber}";
                continue;
            }

            $startDate = collect($allDates)->min();
            $endDate = collect($allDates)->max();
            $actualHemisId = $student->hemis_id;

            // Find existing excuse or create new
            $excuse = AbsenceExcuse::where('student_hemis_id', $actualHemisId)
                ->where('start_date', $startDate->format('Y-m-d'))
                ->where('end_date', $endDate->format('Y-m-d'))
                ->first();

            if ($excuse) {
                $needsUpdate = false;
                if (empty($excuse->file_path) || $excuse->file_path === '') {
                    $excuse->file_path = $docLink;
                    $needsUpdate = true;
                }
                if (empty($excuse->approved_pdf_path) && $certPdf) {
                    $excuse->approved_pdf_path = $certPdf;
                    $needsUpdate = true;
                }
                if (empty($excuse->reviewed_by_name)) {
                    $excuse->reviewed_by_name = $reviewedByName;
                    $excuse->reviewed_by = $reviewedById;
                    $needsUpdate = true;
                }
                if ($needsUpdate) {
                    $excuse->save();
                    $updated++;
                }
            } else {
                $excuse = AbsenceExcuse::create([
                    'student_id' => $student->id,
                    'student_hemis_id' => $actualHemisId,
                    'student_full_name' => $student->full_name ?? $student->short_name,
                    'group_name' => $student->group_name,
                    'department_name' => $student->department_name,
                    'reason' => 'kasallik',
                    'start_date' => $startDate,
                    'end_date' => $endDate,
                    'doc_number' => null,
                    'description' => 'Kasallik (vaqtincha mehnatga layoqatsizlik)',
                    'file_path' => $docLink,
                    'file_original_name' => basename($docLink),
                    'status' => 'approved',
                    'approved_pdf_path' => $certPdf,
                    'reviewed_by' => $reviewedById,
                    'reviewed_by_name' => $reviewedByName,
                    'reviewed_at' => now(),
                    'verification_token' => Str::uuid()->toString(),
                ]);
                $imported++;
            }

            // Create makeups for each subject
            foreach ($subjects as $subj) {
                $subjectName = trim($subj['name']);
                $subjectId = $subj['id'] ?? null;
                $testKeys = $subj['tests']['keys'] ?? [];
                $dates = $subj['dates'];

                foreach ($testKeys as $testKey) {
                    $assessmentType = strtolower($testKey);
                    $assessmentTypeCode = $testKey;

                    $originalDate = null;
                    $makeupEndDate = null;

                    switch ($testKey) {
                        case 'JN':
                            if (!empty($dates['jn']['start'])) {
                                $originalDate = Carbon::createFromFormat('d.m.Y', $dates['jn']['start'])->format('Y-m-d');
                            }
                            if (!empty($dates['jn']['end'])) {
                                $makeupEndDate = Carbon::createFromFormat('d.m.Y', $dates['jn']['end'])->format('Y-m-d');
                            }
                            break;
                        case 'ON':
                            if (!empty($dates['on'])) {
                                $originalDate = Carbon::createFromFormat('d.m.Y', $dates['on'])->format('Y-m-d');
                            }
                            break;
                        case 'YN':
                            if (!empty($dates['yn'])) {
                                $originalDate = Carbon::createFromFormat('d.m.Y', $dates['yn'])->format('Y-m-d');
                            }
                            break;
                        case 'YN_TEST':
                            if (!empty($dates['yn_test'])) {
                                $originalDate = Carbon::createFromFormat('d.m.Y', $dates['yn_test'])->format('Y-m-d');
                            }
                            break;
                    }

                    if (!$originalDate) continue;

                    $exists = AbsenceExcuseMakeup::where('absence_excuse_id', $excuse->id)
                        ->where('subject_name', $subjectName)
                        ->where('assessment_type', $assessmentType)
                        ->where('original_date', $originalDate)
                        ->exists();

                    if ($exists) {
                        $skipped++;
                        continue;
                    }

                    AbsenceExcuseMakeup::create([
                        'absence_excuse_id' => $excuse->id,
                        'student_id' => $student->id,
                        'subject_name' => $subjectName,
                        'subject_id' => $subjectId,
                        'assessment_type' => $assessmentType,
                        'assessment_type_code' => $assessmentTypeCode,
                        'original_date' => $originalDate,
                        'makeup_end_date' => $makeupEndDate,
                        'status' => 'scheduled',
                    ]);
                    $makeupsCreated++;
                }
            }
        }

        $this->info("Import completed:");
        $this->info("  New excuses: {$imported}");
        $this->info("  Updated: {$updated}");
        $this->info("  Makeups created: {$makeupsCreated}");
        $this->info("  Skipped (duplicates): {$skipped}");

        if (!empty($errors)) {
            $this->warn("Errors (" . count($errors) . "):");
            foreach ($errors as $error) {
                $this->warn("  {$error}");
            }
        }
    }

    private function getData(): array
    {
        return [
            ['student_id_number' => '368221100217', 'subjects' => '[{"id":"401682","name":"Akusherlik va ginekologiya","tests":{"keys":["JN","ON"],"labels":["Joriy nazorat (JN)","Oraliq nazorat (ON)"]},"dates":{"jn":{"start":"05.02.2026","end":"09.02.2026"},"on":"10.02.2026","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/JUMAYEV_UMIDJON_BAHROMJONOVICH_368221100217_20260205_115958.pdf', 'reviewed_by' => '{"custom_user_id":5,"custom_full_name":"Samatov Maqsud"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/1_JUMAYEV_UMIDJON_BAHROMJONOVICH.pdf"}'],
            ['student_id_number' => '368221100217', 'subjects' => '[{"id":"401682","name":"Akusherlik va ginekologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"05.02.2026","end":"11.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/JUMAYEV_UMIDJON_BAHROMJONOVICH_368221100217_20260205_120651.pdf', 'reviewed_by' => '{"custom_user_id":1,"custom_full_name":"Super Admin"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/2_JUMAYEV_UMIDJON_BAHROMJONOVICH.pdf"}'],
            ['student_id_number' => '368221100733', 'subjects' => '[{"id":"408287","name":"Xirurgik kasalliklar","tests":{"keys":["JN","ON","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Oraliq nazorat (ON)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"06.02.2026","end":"07.02.2026"},"on":"09.02.2026","yn":"10.02.2026","yn_test":"11.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDUSAMADOVA_NOZIMA_BAXROM_QIZI_368221100733_20260206_073103.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/3_ABDUSAMADOVA_NOZIMA_BAXROM_QIZI.pdf"}'],
            ['student_id_number' => '368221100733', 'subjects' => '[{"id":"408287","name":"Xirurgik kasalliklar","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"06.02.2026","end":"14.02.2026"},"on":"","yn":"16.02.2026","yn_test":"17.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDUSAMADOVA_NOZIMA_BAXROM_QIZI_368221100733_20260206_112426.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/4_ABDUSAMADOVA_NOZIMA_BAXROM_QIZI.pdf"}'],
            ['student_id_number' => '368231100693', 'subjects' => '[{"id":"413791","name":"Umumiy xirurgiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"07.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/CHORIYEV_AKMAL_CHORIYEVICH_368231100693_20260207_033155.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/5_CHORIYEV_AKMAL_CHORIYEVICH.pdf"}'],
            ['student_id_number' => '368251100868', 'subjects' => '[{"id":"415420","name":"Dinshunoslik","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"09.02.2026","end":"10.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"415421","name":"O\u2018zbek tilining sohada qo\u2018llanilishi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"07.02.2026","end":"10.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"415425","name":"Odam anatomiyasi ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"10.02.2026","end":"10.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"415422","name":"Rus tili","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"07.02.2026","end":"09.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"415423","name":"Tibbiy biologiya. Umumiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"10.02.2026","end":"10.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSULMANOVA_NOZIMA_JAMSHID_QIZI_368251100868_20260207_055201.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/6_MUSULMANOVA_NOZIMA_JAMSHID_QIZI.pdf"}'],
            ['student_id_number' => '368211100595', 'subjects' => '[{"id":"422152","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"09.02.2026","end":"11.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSTOFAQULOVA_CHAROS_ALISHER_QIZI_368211100595_20260209_050452.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/11_MUSTOFAQULOVA_CHAROS_ALISHER_QIZI.pdf"}'],
            ['student_id_number' => '368251101241', 'subjects' => '[{"id":"421813","name":"Akusherlik va ginekologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"09.02.2026","end":"13.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSALOVA_LOBAR_KAMOL_QIZI_368251101241_20260209_074410.jpg', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/12_MUSALOVA_LOBAR_KAMOL_QIZI.pdf"}'],
            ['student_id_number' => '368231100497', 'subjects' => '[{"id":"423611","name":"Umumiy xirurgiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"12.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XAZRATOVA_HULKAROY_ZAFAR_QIZI_368231100497_20260209_095920.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/14_XAZRATOVA_HULKAROY_ZAFAR_QIZI.pdf"}'],
            ['student_id_number' => '368221100217', 'subjects' => '[{"id":"422010","name":"Akusherlik va ginekologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"09.02.2026","end":"16.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/JUMAYEV_UMIDJON_BAHROMJONOVICH_368221100217_20260209_100941.pdf', 'reviewed_by' => '{"custom_user_id":1,"custom_full_name":"Super Admin"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/16_JUMAYEV_UMIDJON_BAHROMJONOVICH.pdf"}'],
            ['student_id_number' => '368211100595', 'subjects' => '[{"id":"422152","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"09.02.2026","end":"16.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSTOFAQULOVA_CHAROS_ALISHER_QIZI_368211100595_20260209_101506.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/18_MUSTOFAQULOVA_CHAROS_ALISHER_QIZI.pdf"}'],
            ['student_id_number' => '368211100045', 'subjects' => '[{"id":"422152","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"09.02.2026","end":"10.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDINAZAROVA_MUXLISA_AZAMAT_QIZI_368211100045_20260209_105628.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/19_ABDINAZAROVA_MUXLISA_AZAMAT_QIZI.pdf"}'],
            ['student_id_number' => '368231100063', 'subjects' => '[{"id":"423840","name":"Ichki kasalliklar propedevtikasi (a)","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"11.02.2026"}},{"id":"423831","name":"Patologik anatomiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"12.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/KARIMOV_SARDORBEK_KOMIL_OGLI_368231100063_20260209_110508.jpg', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/20_KARIMOV_SARDORBEK_KOMIL_OGLI.pdf"}'],
            ['student_id_number' => '368211100103', 'subjects' => '[{"id":"422152","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"10.02.2026","end":"16.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/NORBOYEVA_ZARINA_MIRKOMIL_QIZI_368211100103_20260209_115943.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/21_NORBOYEVA_ZARINA_MIRKOMIL_QIZI.pdf"}'],
            ['student_id_number' => '368211100676', 'subjects' => '[{"id":"432012","name":"Ichki kasalliklar","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"11.02.2026","end":"12.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/QILICHEV_BEKZOD_SHERALIYEVICH_368211100676_20260211_045526.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/24_QILICHEV_BEKZOD_SHERALIYEVICH.pdf"}'],
            ['student_id_number' => '368221100675', 'subjects' => '[{"id":"432221","name":"Endokrinologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"11.02.2026"}},{"id":"432219","name":"Urologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"12.02.2026","end":"13.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDULLAYEVA_DILNORA_KOMIL_QIZI_368221100675_20260211_105307.jpg', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/26_ABDULLAYEVA_DILNORA_KOMIL_QIZI.pdf"}'],
            ['student_id_number' => '368251101107', 'subjects' => '[{"id":"435740","name":"Falsafa","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"13.02.2026","end":"16.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"435746","name":"Gistologiya, sitologiya, embriologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"17.02.2026","end":"19.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"435741","name":"O\u2018zbek tilining sohada qo\u2018llanilishi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"20.02.2026","end":"21.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"435745","name":"Odam anatomiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"21.02.2026","end":"23.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"435742","name":"Rus tili","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"24.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"435747","name":"Tanishuv amaliyoti","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"24.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"435744","name":"Tibbiy kimyo","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"25.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XUDOYBERGANOVA_MARJONA_UMARBEK_QIZI_368251101107_20260211_110105.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/27_XUDOYBERGANOVA_MARJONA_UMARBEK_QIZI.pdf"}'],
            ['student_id_number' => '368251101241', 'subjects' => '[{"id":"437132","name":"Akusherlik va ginekologiya","tests":{"keys":["YN","YN_TEST"],"labels":["Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"17.02.2026","yn_test":"18.02.2026"}},{"id":"437133","name":"Pediatriya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"14.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSALOVA_LOBAR_KAMOL_QIZI_368251101241_20260212_105258.jpg', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/29_MUSALOVA_LOBAR_KAMOL_QIZI.pdf"}'],
            ['student_id_number' => '368211100651', 'subjects' => '[{"id":"437470","name":"Otorinoloringologiya va stomatologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"13.02.2026","end":"19.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/TOHIROVA_SHAHZODA_BAHODIR_QIZI_368211100651_20260212_120019.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/30_TOHIROVA_SHAHZODA_BAHODIR_QIZI.pdf"}'],
            ['student_id_number' => '368251100187', 'subjects' => '[{"id":"445951","name":"Gistologiya, sitologiya, embriologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"14.02.2026","end":"17.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"445948","name":"Tibbiy va biologik fizika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"14.02.2026","end":"17.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"445950","name":"Tibbiyotda axborot texnologiyalari","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"14.02.2026","end":"17.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ERKINOV_ABDULAZIZ_SOTVOLDI_OGLI_368251100187_20260214_065922.jpg', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/32_ERKINOV_ABDULAZIZ_SOTVOLDI_OGLI.pdf"}'],
            ['student_id_number' => '368211100595', 'subjects' => '[{"id":"442584","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["YN","YN_TEST"],"labels":["Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"17.02.2026","yn_test":"18.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSTOFAQULOVA_CHAROS_ALISHER_QIZI_368211100595_20260214_074510.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/33_MUSTOFAQULOVA_CHAROS_ALISHER_QIZI.pdf"}'],
            ['student_id_number' => '368211100200', 'subjects' => '[{"id":"452470","name":"Oftalmologiya","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"16.02.2026","end":"18.02.2026"},"on":"","yn":"19.02.2026","yn_test":"19.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/RAXIMOV_NURALI_BOTIRALI_OGLI_368211100200_20260216_073301.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/34_RAXIMOV_NURALI_BOTIRALI_OGLI.pdf"}'],
            ['student_id_number' => '368211100243', 'subjects' => '[{"id":"452809","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"16.02.2026","end":"18.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/CHORSHANBIYEVA_SHOXISTA_OYBEK_QIZI_368211100243_20260216_091756.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/35_CHORSHANBIYEVA_SHOXISTA_OYBEK_QIZI.pdf"}'],
            ['student_id_number' => '368211100676', 'subjects' => '[{"id":"452466","name":"Ichki kasalliklar","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"16.02.2026","end":"17.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/QILICHEV_BEKZOD_SHERALIYEVICH_368211100676_20260216_094521.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/36_QILICHEV_BEKZOD_SHERALIYEVICH.pdf"}'],
            ['student_id_number' => '368211100332', 'subjects' => '[{"id":"452923","name":"Nevrologiya, bolalar nevrologiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"16.02.2026","end":"19.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/RAHMATULLAYEV_XOLMUROD_ULUGBEK_OGLI_368211100332_20260216_103255.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/37_RAHMATULLAYEV_XOLMUROD_ULUGBEK_OGLI.pdf"}'],
            ['student_id_number' => '368251101385', 'subjects' => '[{"id":"456174","name":"Odam anatomiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"16.02.2026","end":"16.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XALILOVA_SABRINA_BAXODIR_QIZI_368251101385_20260216_111959.png', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/38_XALILOVA_SABRINA_BAXODIR_QIZI.pdf"}'],
            ['student_id_number' => '368251101385', 'subjects' => '[{"id":"456174","name":"Odam anatomiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"16.02.2026","end":"16.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XALILOVA_SABRINA_BAXODIR_QIZI_368251101385_20260216_112223.png', 'reviewed_by' => '{"custom_user_id":1,"custom_full_name":"Super Admin"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/40_XALILOVA_SABRINA_BAXODIR_QIZI.pdf"}'],
            ['student_id_number' => '368211100585', 'subjects' => '[{"id":"457582","name":"Xirurgik kasalliklar","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"18.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/NORMURADOVA_SHAHLO_AHROR_QIZI_368211100585_20260217_074059.pdf', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/41_NORMURADOVA_SHAHLO_AHROR_QIZI.pdf"}'],
            ['student_id_number' => '368221100088', 'subjects' => '[{"id":"469252","name":"Dermatovenerologiya va bolalar dermatovenerologiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"19.02.2026","end":"21.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/SHERBOYEVA_LAYLO_XAYOM_QIZI_368221100088_20260219_053342.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/45_SHERBOYEVA_LAYLO_XAYOM_QIZI.pdf"}'],
            ['student_id_number' => '368221100088', 'subjects' => '[{"id":"469252","name":"Dermatovenerologiya va bolalar dermatovenerologiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"19.02.2026","end":"21.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/SHERBOYEVA_LAYLO_XAYOM_QIZI_368221100088_20260219_054049.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/46_SHERBOYEVA_LAYLO_XAYOM_QIZI.pdf"}'],
            ['student_id_number' => '368211100221', 'subjects' => '[{"id":"467808","name":"Ichki kasalliklar","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"19.02.2026","end":"20.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BOQIBOYEV_ASADBEK_ABDURAXIM_OGLI_368211100221_20260219_073113.jpeg', 'reviewed_by' => '{"custom_user_id":15,"custom_full_name":"Botirov Davron Abduraxmonovich"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/47_BOQIBOYEV_ASADBEK_ABDURAXIM_OGLI.pdf"}'],
            ['student_id_number' => '368251101385', 'subjects' => '[{"id":"476641","name":"Odam anatomiyasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"20.02.2026","end":"20.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XALILOVA_SABRINA_BAXODIR_QIZI_368251101385_20260220_040203.png', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/50_XALILOVA_SABRINA_BAXODIR_QIZI.pdf"}'],
            ['student_id_number' => '368221100441', 'subjects' => '[{"id":"474680","name":"Ichki kasalliklar, Kasb kasalliklari ","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"20.02.2026","end":"28.02.2026"},"on":"","yn":"02.03.2026","yn_test":"03.03.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDURAXMONOVA_MUNIRA_SHERZOD_QIZI_368221100441_20260220_072433.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/53_ABDURAXMONOVA_MUNIRA_SHERZOD_QIZI.pdf"}'],
            ['student_id_number' => '368231100382', 'subjects' => '[{"id":"474913","name":"Eipidemiologiya. Harbiy epidemiologiya (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"24.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"474916","name":"Kommunal gigiyena  ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"21.02.2026","end":"21.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"474919","name":"Mehnat gigiyenasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"20.02.2026","end":"20.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"474918","name":"Ovqatlanish gigiyenasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"23.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"474911","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"26.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"474922","name":"Xirurgik kasalliklar","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"25.02.2026","end":"25.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDIRAIMOV_JASUR_ABDIMUROD_OGLI_368231100382_20260220_092453.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/54_ABDIRAIMOV_JASUR_ABDIMUROD_OGLI.pdf"}'],
            ['student_id_number' => '368231100382', 'subjects' => '[{"id":"474910","name":"Patologik anatomiya","tests":{"keys":["YN"],"labels":["Yakuniy nazorat (YN OSKE)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"25.02.2026","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDIRAIMOV_JASUR_ABDIMUROD_OGLI_368231100382_20260220_114614.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/55_ABDIRAIMOV_JASUR_ABDIMUROD_OGLI.pdf"}'],
            ['student_id_number' => '368231100382', 'subjects' => '[{"id":"474910","name":"Patologik anatomiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"25.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDIRAIMOV_JASUR_ABDIMUROD_OGLI_368231100382_20260220_114935.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/56_ABDIRAIMOV_JASUR_ABDIMUROD_OGLI.pdf"}'],
            ['student_id_number' => '368241100811', 'subjects' => '[{"id":"479888","name":"Bolalar kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"479884","name":"Ichki kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"479880","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"25.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"479879","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"479876","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"479877","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDURAXMANOVA_MOHICHEHRA_OLIM_QIZI_368241100811_20260221_065548.jpg', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/57_ABDURAXMANOVA_MOHICHEHRA_OLIM_QIZI.pdf"}'],
            ['student_id_number' => '368251100868', 'subjects' => '[{"id":"492115","name":"Gistologiya, sitologiya, embriologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"24.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"492120","name":"Psixologiya va pedagogika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"24.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUSULMANOVA_NOZIMA_JAMSHID_QIZI_368251100868_20260223_103740.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/66_MUSULMANOVA_NOZIMA_JAMSHID_QIZI.pdf"}'],
            ['student_id_number' => '368211100102', 'subjects' => '[{"id":"488293","name":"Epidemiologiya, XE","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MENGLIBAYEVA_NOZIMA_IKROM_QIZI_368211100102_20260223_132254.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/69_MENGLIBAYEVA_NOZIMA_IKROM_QIZI.pdf"}'],
            ['student_id_number' => '368211100449', 'subjects' => '[{"id":"488639","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"488636","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/AXMADOVA_DURDONA_KAMOL_QIZI_368211100449_20260223_145656.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/70_AXMADOVA_DURDONA_KAMOL_QIZI.pdf"}'],
            ['student_id_number' => '368211100460', 'subjects' => '[{"id":"488636","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BARDIN_ARKADIY_NIKOLAYEVICH_368211100460_20260223_151336.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/71_BARDIN_ARKADIY_NIKOLAYEVICH.pdf"}'],
            ['student_id_number' => '368221100199', 'subjects' => '[{"id":"489737","name":"Yukumli kasalliklar. Bolalar yuqumli kasalliklari","tests":{"keys":["YN","YN_TEST"],"labels":["Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"25.02.2026","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ZUBKOVA_NASIBA_VLADIMIROVNA_368221100199_20260223_151402.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/72_ZUBKOVA_NASIBA_VLADIMIROVNA.pdf"}'],
            ['student_id_number' => '368211100142', 'subjects' => '[{"id":"488636","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/NAZAROV_ASADBEK_ANVARBEKOVICH_368211100142_20260223_152256.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/73_NAZAROV_ASADBEK_ANVARBEKOVICH.pdf"}'],
            ['student_id_number' => '368221100047', 'subjects' => '[{"id":"489738","name":"Yuqumli kasalliklar. Bolalar yuqumli kasalliklari","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XAYDAROVA_NIGINA_ORIF_QIZI_368221100047_20260223_152419.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/74_XAYDAROVA_NIGINA_ORIF_QIZI.pdf"}'],
            ['student_id_number' => '368221100047', 'subjects' => '[{"id":"489738","name":"Yuqumli kasalliklar. Bolalar yuqumli kasalliklari","tests":{"keys":["YN","YN_TEST"],"labels":["Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"25.02.2026","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XAYDAROVA_NIGINA_ORIF_QIZI_368221100047_20260223_152646.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/75_XAYDAROVA_NIGINA_ORIF_QIZI.pdf"}'],
            ['student_id_number' => '368211100209', 'subjects' => '[{"id":"488639","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"23.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"488636","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/RIJKOVA_KSENIYA_ANDREYEVNA_368211100209_20260223_161323.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/76_RIJKOVA_KSENIYA_ANDREYEVNA.pdf"}'],
            ['student_id_number' => '368211100468', 'subjects' => '[{"id":"493759","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"493756","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDURAXMANOVA_XILOLA_SHUXRATOVNA_368211100468_20260224_020343.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/77_ABDURAXMANOVA_XILOLA_SHUXRATOVNA.pdf"}'],
            ['student_id_number' => '368241100220', 'subjects' => '[{"id":"495932","name":"Valeologiya asoslari","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"24.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/CHORIYEV_DILSHODBEK_FAXRIDDIN_OGLI_368241100220_20260224_062352.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/80_CHORIYEV_DILSHODBEK_FAXRIDDIN_OGLI.pdf"}'],
            ['student_id_number' => '368211100635', 'subjects' => '[{"id":"493759","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"493756","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ISAQOV_IBROHIMJON_INAQJON_OGLI_368211100635_20260224_070345.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/84_ISAQOV_IBROHIMJON_INAQJON_OGLI.pdf"}'],
            ['student_id_number' => '368231100472', 'subjects' => '[{"id":"495616","name":"Bolalar kasalliklar propedevtikasi (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495610","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495612","name":"Ichki kasalliklar propedevtikasi (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"495624","name":"Ilmiy-tadqiqot asoslari (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495611","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495607","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495608","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495609","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDUKARIMOV_YAHYO_RAVSHAN_OGLI_368231100472_20260224_072315.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/85_ABDUKARIMOV_YAHYO_RAVSHAN_OGLI.pdf"}'],
            ['student_id_number' => '368221100511', 'subjects' => '[{"id":"495162","name":"Bolalar xirurgiyasi","tests":{"keys":["JN","YN"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)"]},"dates":{"jn":{"start":"24.02.2026","end":"06.03.2026"},"on":"","yn":"07.03.2026","yn_test":""}},{"id":"495161","name":"Xirurgik kasalliklar","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"24.02.2026","end":"17.03.2026"},"on":"","yn":"18.03.2026","yn_test":"19.03.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/JORAYEVA_AZIZA_ABDUMALIK_QIZI_368221100511_20260224_072804.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/86_JORAYEVA_AZIZA_ABDUMALIK_QIZI.pdf"}'],
            ['student_id_number' => '368221100224', 'subjects' => '[{"id":"493616","name":"Endokrinologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"25.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/MUHAMMADOV_YUSUFBEK_UMIDJONOVICH_368221100224_20260224_075122.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/88_MUHAMMADOV_YUSUFBEK_UMIDJONOVICH.pdf"}'],
            ['student_id_number' => '368211100135', 'subjects' => '[{"id":"493759","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"493756","name":"Psixologiya. Tibbiy psixologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"26.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BAHODIRJONOV_TEMUR_LAZIZXON_OGLI_368211100135_20260224_075201.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/89_BAHODIRJONOV_TEMUR_LAZIZXON_OGLI.pdf"}'],
            ['student_id_number' => '368241100923', 'subjects' => '[{"id":"495747","name":"Gigiyena, harbiy gigiyena. Tibbiy ekologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"25.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"495745","name":"Mikrobiologiya, virusologiya, immunologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"25.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"495743","name":"Psixologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"25.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XALILOV_ADHAMBEK_BEKZOD_OGLI_368241100923_20260224_091213.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/90_XALILOV_ADHAMBEK_BEKZOD_OGLI.pdf"}'],
            ['student_id_number' => '368231100703', 'subjects' => '[{"id":"495615","name":"Bolalar kasalliklar propedevtikasi (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495610","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495613","name":"Ichki kasalliklar propedevtikasi (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495623","name":"Ilmiy-tadqiqot asoslari (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495611","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495607","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495608","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495609","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/XOLMATOVA_DILINUR_OTABEKOVNA_368231100703_20260224_103035.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/91_XOLMATOVA_DILINUR_OTABEKOVNA.pdf"}'],
            ['student_id_number' => '368231100626', 'subjects' => '[{"id":"495617","name":"Bolalar kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495610","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495611","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495607","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495608","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"495609","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"24.02.2026","end":"02.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/GIYOSIDDINOV_ISMOILBEK_XUSNIDDIN_OGLI_368231100626_20260224_135552.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/92_GIYOSIDDINOV_ISMOILBEK_XUSNIDDIN_OGLI.pdf"}'],
            ['student_id_number' => '368221100216', 'subjects' => '[{"id":"498739","name":"Endokrinologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"25.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BABADJANOV_BEKZOD_BOTIROVICH_368221100216_20260225_060249.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/93_BABADJANOV_BEKZOD_BOTIROVICH.pdf"}'],
            ['student_id_number' => '368221100081', 'subjects' => '[{"id":"498739","name":"Endokrinologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"25.02.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/TURAKULOV_SAMANDAR_OLIMJONOVICH_368221100081_20260225_084117.pdf', 'reviewed_by' => '{"custom_user_id":9,"custom_full_name":"O\'ralov muhammadzafar"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/95_TURAKULOV_SAMANDAR_OLIMJONOVICH.pdf"}'],
            ['student_id_number' => '368211100460', 'subjects' => '[{"id":"498882","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BARDIN_ARKADIY_NIKOLAYEVICH_368211100460_20260225_091111.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/96_BARDIN_ARKADIY_NIKOLAYEVICH.pdf"}'],
            ['student_id_number' => '368231100401', 'subjects' => '[{"id":"500522","name":"Mehnat gigiyenasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"25.02.2026","end":"26.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"500514","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BORONOVA_GULHAYO_BAHROM_QIZI_368231100401_20260225_092610.pdf', 'reviewed_by' => '{"custom_user_id":9,"custom_full_name":"O\'ralov muhammadzafar"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/98_BORONOVA_GULHAYO_BAHROM_QIZI.pdf"}'],
            ['student_id_number' => '368251101407', 'subjects' => '[{"id":"502355","name":"Dinshunoslik","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"25.02.2026","end":"26.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"502361","name":"Gistologiya, sitologiya, embriologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"502356","name":"O\u2018zbek tilining sohada qo\u2018llanilishi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"502360","name":"Odam anatomiyasi ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"502357","name":"Rus tili","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"502358","name":"Tibbiy biologiya. Umumiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"502359","name":"Tibbiy kimyo","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BOBOGULOVA_SABRINA_ISKANDAR_QIZI_368251101407_20260225_094324.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/99_BOBOGULOVA_SABRINA_ISKANDAR_QIZI.pdf"}'],
            ['student_id_number' => '368211100676', 'subjects' => '[{"id":"498538","name":"Pediatriya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"25.02.2026","end":"26.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/QILICHEV_BEKZOD_SHERALIYEVICH_368211100676_20260225_105738.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/100_QILICHEV_BEKZOD_SHERALIYEVICH.pdf"}'],
            ['student_id_number' => '368251100961', 'subjects' => '[{"id":"505990","name":"Biokimyo","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"505993","name":"Gigiyena, harbiy gigiyena. Tibbiy ekologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"505995","name":"Hayot faoliyati xavfsizligi. Fuqaro muhofazasi","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"505991","name":"Mikrobiologiya, virusologiya, immunologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"505992","name":"Normal fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"505989","name":"Psixologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"505994","name":"Valeologiya asoslari","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"10.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDURAXMONOVA_BOGDAGUL_NORQUVVAT_QIZI_368251100961_20260226_033848.jpeg', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/102_ABDURAXMONOVA_BOGDAGUL_NORQUVVAT_QIZI.pdf"}'],
            ['student_id_number' => '368211100142', 'subjects' => '[{"id":"504005","name":" Nevrologiya, tibbiy genetika","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/NAZAROV_ASADBEK_ANVARBEKOVICH_368211100142_20260226_062322.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/108_NAZAROV_ASADBEK_ANVARBEKOVICH.pdf"}'],
            ['student_id_number' => '368211100763', 'subjects' => '[{"id":"503654","name":"Anesteziologiya va reanimatologiya","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"28.02.2026","end":"05.03.2026"},"on":"","yn":"11.03.2026","yn_test":"12.03.2026"}},{"id":"503653","name":"Ichki kasalliklar","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"07.03.2026","yn_test":"09.03.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/RASULOVA_NAFISA_ALISHER_QIZI_368211100763_20260226_062550.pdf', 'reviewed_by' => '{"custom_user_id":1,"custom_full_name":"Super Admin"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/109_RASULOVA_NAFISA_ALISHER_QIZI.pdf"}'],
            ['student_id_number' => '368241100569', 'subjects' => '[{"id":"506244","name":"Analitik kimyo","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"07.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"506247","name":"Farmatsevtik etika va deontologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"07.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"506243","name":"Organik kimyo","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"07.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"506245","name":"Patologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"07.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"506246","name":"Valeologiya asoslari","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"07.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDIKARIMOV_HUSAN_AXROR_OGLI_368241100569_20260226_063345.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/110_ABDIKARIMOV_HUSAN_AXROR_OGLI.pdf"}'],
            ['student_id_number' => '368241100492', 'subjects' => '[{"id":"506174","name":"Normal fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/SAFAROVA_ZARNIGOR_ZAFAROVNA_368241100492_20260226_094828.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/116_SAFAROVA_ZARNIGOR_ZAFAROVNA.pdf"}'],
            ['student_id_number' => '368231100318', 'subjects' => '[{"id":"505484","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"26.02.2026","end":"26.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/CHORIYEV_FIRDAVS_FARXODOVICH_368231100318_20260226_105546.pdf', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/118_CHORIYEV_FIRDAVS_FARXODOVICH.pdf"}'],
            ['student_id_number' => '368231100652', 'subjects' => '[{"id":"510985","name":"Bolalar kasalliklar propedevtikasi (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510979","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510981","name":"Ichki kasalliklar propedevtikasi (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510993","name":"Ilmiy-tadqiqot asoslari (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510980","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510976","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510977","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510978","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/BAXTIYOROV_ASILIDDIN_BILOLIDDIN_OGLI_368231100652_20260227_043107.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/122_BAXTIYOROV_ASILIDDIN_BILOLIDDIN_OGLI.pdf"}'],
            ['student_id_number' => '368221100249', 'subjects' => '[{"id":"508988","name":"Fundamental otorinoloringologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/JUMABOYEVA_SHAXNOZABONU_SHAVKAT_QIZI_368221100249_20260227_050116.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/125_JUMABOYEVA_SHAXNOZABONU_SHAVKAT_QIZI.pdf"}'],
            ['student_id_number' => '368251100074', 'subjects' => '[{"id":"511296","name":"Biokimyo","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"12.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"511295","name":"Dinshunoslik","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"12.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"511299","name":"Gigiyena, harbiy gigiyena. Tibbiy ekologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"12.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"511298","name":"Mikrobiologiya, virusologiya, immunologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"12.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"511297","name":"Normal fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"12.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"511301","name":"Valeologiya asoslari","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"12.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/NARZULLAYEVA_SHOHIDA_KAMOLIDDIN_QIZI_368251100074_20260227_074610.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/127_NARZULLAYEVA_SHOHIDA_KAMOLIDDIN_QIZI.pdf"}'],
            ['student_id_number' => '368211100694', 'subjects' => '[{"id":"508776","name":"Ichki kasalliklar","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/DJALILOV_MUXAMMADALI_OTABEKOVICH_368211100694_20260227_075713.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/128_DJALILOV_MUXAMMADALI_OTABEKOVICH.pdf"}'],
            ['student_id_number' => '368221100757', 'subjects' => '[{"id":"510224","name":"Sud tibbiyoti, vrach faoliyatining huquqiy asoslari ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"27.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ABDIMOMINOVA_DILRABO_SHERBOY_QIZI_368221100757_20260227_081111.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/129_ABDIMOMINOVA_DILRABO_SHERBOY_QIZI.pdf"}'],
            ['student_id_number' => '368231100612', 'subjects' => '[{"id":"510984","name":"Bolalar kasalliklar propedevtikasi (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510979","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510982","name":"Ichki kasalliklar propedevtikasi (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510992","name":"Ilmiy-tadqiqot asoslari (a)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510980","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510976","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510977","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510978","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ISHKARAYEV_SHOXRUX_SHERALIYEVICH_368231100612_20260227_090820.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/130_ISHKARAYEV_SHOXRUX_SHERALIYEVICH.pdf"}'],
            ['student_id_number' => '368231100825', 'subjects' => '[{"id":"510986","name":"Bolalar kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"28.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"510979","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"510983","name":"Ichki kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"28.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"510980","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"28.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"510977","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}},{"id":"510978","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"28.02.2026","end":"28.02.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/EGAMMURODOV_OTABEK_ABDUHAKIMOVICH_368231100825_20260227_113640.jpg', 'reviewed_by' => '{"custom_user_id":4,"custom_full_name":"Aziza G\'oziyeva"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/131_EGAMMURODOV_OTABEK_ABDUHAKIMOVICH.pdf"}'],
            ['student_id_number' => '368231100601', 'subjects' => '[{"id":"510986","name":"Bolalar kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510979","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510983","name":"Ichki kasalliklar propedevtikasi (b)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510980","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510976","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510977","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"510978","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"27.02.2026","end":"05.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/KAXXOROVA_BAHOR_ZAFAR_QIZI_368231100601_20260227_115830.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/132_KAXXOROVA_BAHOR_ZAFAR_QIZI.pdf"}'],
            ['student_id_number' => '368241100809', 'subjects' => '[{"id":"515745","name":"Bolalar kasalliklar propedevtikasi (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515730","name":"Farmakologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515737","name":"Ichki kasalliklar propedevtikasi (c)","tests":{"keys":["JN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"02.03.2026","end":"13.03.2026"},"on":"","yn":"","yn_test":"14.03.2026"}},{"id":"515744","name":"Ilmiy-tadqiqot asoslari (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515732","name":"Jamoat salomatligi. Marketing, menejment","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515731","name":"Klinik anatomiya (Operativ jarrohlik va topopgrafik anatomiya) ","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515728","name":"Patologik anatomiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515729","name":"Patologik fiziologiya","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}},{"id":"515734","name":"Umumiy xirurgiya (c)","tests":{"keys":["JN"],"labels":["Joriy nazorat (JN)"]},"dates":{"jn":{"start":"02.03.2026","end":"14.03.2026"},"on":"","yn":"","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/ZULFIQAHHOROVA_HILOLAXON_UCHQUNJON_QIZI_368241100809_20260302_065114.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/136_ZULFIQAHHOROVA_HILOLAXON_UCHQUNJON_QIZI.pdf"}'],
            ['student_id_number' => '368221100090', 'subjects' => '[{"id":"515347","name":"Sud tibbiyoti, vrach faoliyatining huquqiy asoslari ","tests":{"keys":["JN","YN"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)"]},"dates":{"jn":{"start":"02.03.2026","end":"05.03.2026"},"on":"","yn":"06.03.2026","yn_test":""}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/YUSUPOVA_LAYLO_BAHODIR_QIZI_368221100090_20260302_072632.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/140_YUSUPOVA_LAYLO_BAHODIR_QIZI.pdf"}'],
            ['student_id_number' => '368211100526', 'subjects' => '[{"id":"513901","name":"Xirurgik kasalliklar","tests":{"keys":["JN","YN","YN_TEST"],"labels":["Joriy nazorat (JN)","Yakuniy nazorat (YN OSKE)","Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"02.03.2026","end":"09.03.2026"},"on":"","yn":"10.03.2026","yn_test":"11.03.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/IBRAGIMOVA_DILNOZA_XAKIM_QIZI_368211100526_20260302_073119.pdf', 'reviewed_by' => '{"custom_user_id":6,"custom_full_name":"Annaqulova Nozima"}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/141_IBRAGIMOVA_DILNOZA_XAKIM_QIZI.pdf"}'],
            ['student_id_number' => '368221100854', 'subjects' => '[{"id":"519027","name":"Oftalmologiya","tests":{"keys":["YN_TEST"],"labels":["Yakuniy nazorat (YN Test)"]},"dates":{"jn":{"start":"","end":""},"on":"","yn":"","yn_test":"03.03.2026"}}]', 'doc_link' => 'https://admission.ttatf.uz/wp-content/talabnoma/documents/RAJABOVA_IRODA_NISHON_QIZI_368221100854_20260303_103313.pdf', 'reviewed_by' => '{"custom_user_id":7,"custom_full_name":"Berdiyarova Mahbuba Olimovna."}', 'certificate' => '{"url_pdf":"https:\/\/admission.ttatf.uz\/wp-content\/talabnoma\/certificates\/144_RAJABOVA_IRODA_NISHON_QIZI.pdf"}'],
        ];
    }
}
