<?php

return [
    // PDF Certificate (permit)
    'cert_title' => 'RETAKE PERMIT',
    'cert_subtitle' => 'Permit for retaking subjects with academic debt',
    'cert_badge_approved' => 'APPROVED',

    'cert_university' => 'TASHKENT MEDICAL UNIVERSITY',
    'cert_filial' => 'TERMEZ BRANCH',

    'label_student' => 'Student name',
    'label_hemis_id' => 'HEMIS ID',
    'label_faculty' => 'Faculty',
    'label_specialty' => 'Specialty',
    'label_course_group' => 'Year · Group',
    'label_uuid' => 'Application UUID',
    'label_submitted_at' => 'Submitted at',

    'section_subjects' => 'Approved subjects',
    'col_num' => '#',
    'col_subject' => 'Subject',
    'col_semester' => 'Semester',
    'col_credit' => 'Credits',
    'col_teacher' => 'Teacher',
    'col_dates' => 'Dates',
    'inline_group' => 'Group',

    'totals_credits' => 'Total: :credits credits',
    'totals_amount' => 'Payment:',

    'sig_section' => 'Approved by',
    'sig_dean' => 'Dean',
    'sig_registrar' => "Registrar's office",
    'sig_academic' => 'Academic department',
    'sig_no_signature' => 'No signature',

    'stamp_note' => 'This document is generated by an electronic system. The QR code can be used to verify authenticity.',
    'verify_label' => 'Verify document:',
    'verify_token' => 'Token:',
    'verify_generated_at' => 'Generated at:',
];
